### PR TITLE
make mermaid.js lib local

### LINKED ISSUE #4: Use local version of mermaid.min.js
The generated html currently fetches `mermaid.min.js` from a cdn on the internet, which is best practice in some contexts but is I think the wrong default in this case : rustdocs can normally be generated and viewed offline.  They should also be impervious to API or url changes 10 years down the road, firewalls, etc.

I think that `mermaid.min.js` should be saved alongside `sidebar-items.js`. Not sure if there's a rustdoc naming convention to adhere to (like "cratename.crateversion.normalname") to avoid conflicts with a similar tool.

### PR DESCRIPTION
**Pull request by lesavonfou**
Hi,

I have created this merge request to solve the issue #4 .
This make the mermaid.js library local.
The main problem I encountered was to move the js file to the right location but using the `build.rs` script did the trick.

As @mdaj06 I am relatively new to the Rust ecosystem therefore any remarks are welcome! :)

__________________

Closes #4

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+    let out_dir = env::var("OUT_DIR").unwrap();
+
+    copy_options.overwrite = true;
+    copy_options.copy_inside = true;
+
+    let mut docs_dir = out_dir;
+    docs_dir.push_str("/../../../../doc");
+
+    fs::create_dir_all(&docs_dir).unwrap();
+    copy_items(&vec!["./doc/js/mermaid.min.js"], &docs_dir, &copy_options).unwrap();
```
Comment (mersinvald) [inline build.rs:15]: 1) There's no need to pass a `vec!` reference, since `copy_items` expects a reference to slice. You can construct slice here instead of vector: `copy_items(&["..."], ...)`

2) As far as I see there's no reason to use the `fs_extra` crate, [fs::copy]](https://doc.rust-lang.org/std/fs/fn.copy.html) should suffice

**Review by mersinvald — COMMENTED** [review]
Awesome, thanks a lot for implementing that, hugely appreciated! :) 

A few comments though, besides what already mentioned in review:

1) what is `doc/img/something`?

2) please add the [include parameter](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) to the Cargo.toml, to tell cargo to upload the js file to crates.io with the package

**Comment by lesavonfou** [comment]
Thanks for the feedback!

1. `src/img/something` was a dummy file used for debugging. It has been removed.
2. I added the `include` field in `Cargo.toml`. I am not sure how to test it though ...

File: build.rs (hunk 1 above)
Comment (lesavonfou) [reply build.rs]: That's what I though as well! The `fs_extra`function  has been replaced by the `std::fs::copy`. I also renamed the function to something more specific. I think it's good enough for the moment.

File: Cargo.toml [hunk 2]
```diff
@@ -8,6 +8,7 @@ categories = ["visualization", "development-tools::build-utils"]
 repository = "https://github.com/mersinvald/aquamarine"
 edition = "2018"
 license = "MIT"
+include = [ "doc/**/*" ]
```
Comment (mersinvald) [inline Cargo.toml:11]: It's not very important, but since there's just one file copied in `build.rs`, I think there should be just one file listed in the `include` too

Comment (lesavonfou) [reply Cargo.toml]: Gotcha

**Comment by mersinvald** [comment]
Great, I'll make a release shortly
